### ISSUE TITLE
bug(class): declared classes not stored in last tick

### ISSUE THREAD

**Issue by apoorvsadana** [madara-alliance/madara#278]
### Is there an existing issue?

- [X] I have searched the existing issues

### Description of bug

`store_block` is only called during ticks as [here](https://github.com/madara-alliance/madara/blob/c73120439ceb2953b18c43e75a7e4613614ed91f/crates/client/mempool/src/block_production.rs#L321-L321). They aren't stored during [`on_block_time`](https://github.com/madara-alliance/madara/blob/c73120439ceb2953b18c43e75a7e4613614ed91f/crates/client/mempool/src/block_production.rs#L344-L344) which causes it changes to not reflect. We should store the declared classes in `on_block_time`

**Comment by apoorvsadana** [comment]
Should be solved in #271

**Comment by cchudant** [comment]
I think the issue you're referring to is something else: the verify_apply step of block import does the store block, we don't need it in block prod
I have fixed another thing which was related to forcing db flush for block production at every block, I believe that's what you're referring to.
Pending block in block prod does not use the block import pipeline yet, and that's why the store block is there
it will use the block improt and i'm also adding the ability to continue the last pending block on start-up, as well as the ability to save the tx pool to disk

**Comment by apoorvsadana** [comment]
I see. I will explain the behaviour I saw which is why I thought this was the issue

- If a class is declared in any tick except the last one, I am able to get the class using `starkli` i.e. its stored inside the DB
- If a class is declared in the last tick (I can force this to happen if tick time = block time, in my case it was actually tick time = 2*block time which shouldn't be possible, created issue #277), then getting the class from starkli was failing

Does this also explain the `db flush` issue?

**Comment by cchudant** [comment]
ah, no it was because i forgot to save the declared class when closing a block. It's fixed yes

**Comment by Trantorian1** [comment]
This was fixed in #271
